# Define a method display_board that prints a 3x3 Tic Tac Toe Board
def display_board
  puts " |    |"
  puts "--------"
  puts " |    |"
  puts "--------"
  puts " |    |"
  puts "Welcome to Tik Tac Toe"
  puts " |    |"
  puts "--------"
  puts " |    |"
  puts "--------"
  puts " |    |"
  puts "What move would x like to make (1-9)?"
  puts ">5"
  puts " |    |"
  puts "--------"
  puts " |  X |"
  puts "--------"
  puts " |    |"
  puts "What move would O like to make (1-9)?"
  puts ">1"
  puts "O|    |"
  puts "--------"
  puts " |  X |"
  puts "--------"
  puts " |    |"
  puts "etc..."
end